global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  # Prometheus se surveille lui-meme
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Metriques Kafka via kafka-exporter
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
